name: Deploy server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t debashish22/authentique ./server
      - name: Publish Image to docker hub
        run: docker push debashish22/authentique:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull debashish22/authentique:latest 
      - name: Delete old container
        run: docker rm -f server-container  
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name server-container -e MONGO_DB_URI='${{ secrets.MONGO_DB_URI }}' -e NODEMAILER_SERVICE='${{ secrets.NODEMAILER_SERVICE }}' debashish22/authentique:latest